### ISSUE TITLE
Client defaults to "active" status

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/evaluation_tools#10]
https://github.com/NOAA-OWP/evaluation_tools/blob/1e3b0701f68977d16371740df802fc180445024f/python/nwis_client/evaluation_tools/nwis_client/iv.py#L83

To more closely mimic the default behavior of NWIS itself, the active status should default to ALL and users should configure their client for the more specific cases of "inactive" and "active".

**Comment by jarq6c** [comment]
You're all determined to make me reconfigure all my workflows. 😝

**Comment by jarq6c** [comment]
@hellkite500 do you want to make this change and submit the PR?
