### ISSUE TITLE
Add gcp_client and events docs to gh-pages deployment

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/evaluation_tools#27]
These subpackages need to be added to the sphinx docs so they are deployed on gh-pages.

**Comment by jarq6c** [comment]
@aaraney Can you document a minimal guide or step-by-step instructions to add new subpackages to the sphinx docs?

**Comment by aaraney** [comment]
Working on that now. I think it makes sense to turn this into a GH action so that they are auto deployed, so I will likely just cover how to add new documentation.
