### ISSUE TITLE
Please update 'About' description with more details

### ISSUE THREAD

**Issue by jarq6c** [NOAA-OWP/evaluation_tools#3]
In response to Andy's request to make individual tools more discoverable, please add more details to the repository's description.

For example,

"Suite of tools for retrieving USGS NWIS observations and evaluating National Water Model (NWM) data."

Is there a better description?

**Comment by HankHerr-NOAA** [comment]
Looks fine to me.  I'll modify the repo Description (I assume that's the change I need to make) when I hear back from Austin that he agrees.

**Comment by HankHerr-NOAA** [comment]
I'm going to change the About description now.  Austin: If you have any modifications to make, let me know and I'll change it again.

Thanks,
Hank

**Comment by HankHerr-NOAA** [comment]
Is there a status prior to Close that I can set this ticket to in order to reflect that I did my work pending approval?  Or should I just close it?

Hank

**Comment by jarq6c** [comment]
We normally reference a commit in a comment and close the ticket. Thanks for updating the description!

**Comment by aaraney** [comment]
@HankHerr-NOAA, looks great! Thanks for updating the description.
